<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_dokuman extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_dokuman_model');
    } 

    /*
     * Listing of tb_dokumen
     */
    function index()
    {
        $data['tb_dokumen'] = $this->Tb_dokuman_model->get_all_tb_dokumen();
        
        $data['_view'] = 'tb_dokuman/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_dokuman
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
		$this->form_validation->set_rules('deskripsi','Deskripsi','required|max_length[100]');
		$this->form_validation->set_rules('file','File','required|max_length[50]');
		$this->form_validation->set_rules('tanggal','Tanggal','required');
		$this->form_validation->set_rules('idJenis','IdJenis','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
				'deskripsi' => $this->input->post('deskripsi'),
				'file' => $this->input->post('file'),
				'tanggal' => $this->input->post('tanggal'),
				'idJenis' => $this->input->post('idJenis'),
            );
            
            $tb_dokuman_id = $this->Tb_dokuman_model->add_tb_dokuman($params);
            redirect('tb_dokuman/index');
        }
        else
        {            
            $data['_view'] = 'tb_dokuman/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_dokuman
     */
    function edit($idDokumen)
    {   
        // check if the tb_dokuman exists before trying to edit it
        $data['tb_dokuman'] = $this->Tb_dokuman_model->get_tb_dokuman($idDokumen);
        
        if(isset($data['tb_dokuman']['idDokumen']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
			$this->form_validation->set_rules('deskripsi','Deskripsi','required|max_length[100]');
			$this->form_validation->set_rules('file','File','required|max_length[50]');
			$this->form_validation->set_rules('tanggal','Tanggal','required');
			$this->form_validation->set_rules('idJenis','IdJenis','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'deskripsi' => $this->input->post('deskripsi'),
					'file' => $this->input->post('file'),
					'tanggal' => $this->input->post('tanggal'),
					'idJenis' => $this->input->post('idJenis'),
                );

                $this->Tb_dokuman_model->update_tb_dokuman($idDokumen,$params);            
                redirect('tb_dokuman/index');
            }
            else
            {
                $data['_view'] = 'tb_dokuman/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_dokuman you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_dokuman
     */
    function remove($idDokumen)
    {
        $tb_dokuman = $this->Tb_dokuman_model->get_tb_dokuman($idDokumen);

        // check if the tb_dokuman exists before trying to delete it
        if(isset($tb_dokuman['idDokumen']))
        {
            $this->Tb_dokuman_model->delete_tb_dokuman($idDokumen);
            redirect('tb_dokuman/index');
        }
        else
            show_error('The tb_dokuman you are trying to delete does not exist.');
    }
    
}
