<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_jenisdokuman extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_jenisdokuman_model');
    } 

    /*
     * Listing of tb_jenisdokumen
     */
    function index()
    {
        $data['tb_jenisdokumen'] = $this->Tb_jenisdokuman_model->get_all_tb_jenisdokumen();
        
        $data['_view'] = 'tb_jenisdokuman/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_jenisdokuman
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
            );
            
            $tb_jenisdokuman_id = $this->Tb_jenisdokuman_model->add_tb_jenisdokuman($params);
            redirect('tb_jenisdokuman/index');
        }
        else
        {            
            $data['_view'] = 'tb_jenisdokuman/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_jenisdokuman
     */
    function edit($idJenis)
    {   
        // check if the tb_jenisdokuman exists before trying to edit it
        $data['tb_jenisdokuman'] = $this->Tb_jenisdokuman_model->get_tb_jenisdokuman($idJenis);
        
        if(isset($data['tb_jenisdokuman']['idJenis']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
                );

                $this->Tb_jenisdokuman_model->update_tb_jenisdokuman($idJenis,$params);            
                redirect('tb_jenisdokuman/index');
            }
            else
            {
                $data['_view'] = 'tb_jenisdokuman/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_jenisdokuman you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_jenisdokuman
     */
    function remove($idJenis)
    {
        $tb_jenisdokuman = $this->Tb_jenisdokuman_model->get_tb_jenisdokuman($idJenis);

        // check if the tb_jenisdokuman exists before trying to delete it
        if(isset($tb_jenisdokuman['idJenis']))
        {
            $this->Tb_jenisdokuman_model->delete_tb_jenisdokuman($idJenis);
            redirect('tb_jenisdokuman/index');
        }
        else
            show_error('The tb_jenisdokuman you are trying to delete does not exist.');
    }
    
}
