<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_user extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_user_model');
    } 

    /*
     * Listing of tb_user
     */
    function index()
    {
        $data['tb_user'] = $this->Tb_user_model->get_all_tb_user();
        
        $data['_view'] = 'tb_user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_user
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('hakAkses','HakAkses','required|max_length[20]');
		$this->form_validation->set_rules('password','Password','required|max_length[50]');
		$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
		$this->form_validation->set_rules('username','Username','required|max_length[20]');
		$this->form_validation->set_rules('email','Email','required|max_length[50]|valid_email');
		$this->form_validation->set_rules('keterangan','Keterangan','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'hakAkses' => $this->input->post('hakAkses'),
				'password' => $this->input->post('password'),
				'nama' => $this->input->post('nama'),
				'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $tb_user_id = $this->Tb_user_model->add_tb_user($params);
            redirect('tb_user/index');
        }
        else
        {            
            $data['_view'] = 'tb_user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_user
     */
    function edit($idUser)
    {   
        // check if the tb_user exists before trying to edit it
        $data['tb_user'] = $this->Tb_user_model->get_tb_user($idUser);
        
        if(isset($data['tb_user']['idUser']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('hakAkses','HakAkses','required|max_length[20]');
			$this->form_validation->set_rules('password','Password','required|max_length[50]');
			$this->form_validation->set_rules('nama','Nama','required|max_length[50]');
			$this->form_validation->set_rules('username','Username','required|max_length[20]');
			$this->form_validation->set_rules('email','Email','required|max_length[50]|valid_email');
			$this->form_validation->set_rules('keterangan','Keterangan','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'hakAkses' => $this->input->post('hakAkses'),
					'password' => $this->input->post('password'),
					'nama' => $this->input->post('nama'),
					'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Tb_user_model->update_tb_user($idUser,$params);            
                redirect('tb_user/index');
            }
            else
            {
                $data['_view'] = 'tb_user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_user you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_user
     */
    function remove($idUser)
    {
        $tb_user = $this->Tb_user_model->get_tb_user($idUser);

        // check if the tb_user exists before trying to delete it
        if(isset($tb_user['idUser']))
        {
            $this->Tb_user_model->delete_tb_user($idUser);
            redirect('tb_user/index');
        }
        else
            show_error('The tb_user you are trying to delete does not exist.');
    }
    
}
