<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_jenisdokuman_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_jenisdokuman by idJenis
     */
    function get_tb_jenisdokuman($idJenis)
    {
        return $this->db->get_where('tb_jenisdokumen',array('idJenis'=>$idJenis))->row_array();
    }
        
    /*
     * Get all tb_jenisdokumen
     */
    function get_all_tb_jenisdokumen()
    {
        $this->db->order_by('idJenis', 'desc');
        return $this->db->get('tb_jenisdokumen')->result_array();
    }
        
    /*
     * function to add new tb_jenisdokuman
     */
    function add_tb_jenisdokuman($params)
    {
        $this->db->insert('tb_jenisdokumen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_jenisdokuman
     */
    function update_tb_jenisdokuman($idJenis,$params)
    {
        $this->db->where('idJenis',$idJenis);
        return $this->db->update('tb_jenisdokumen',$params);
    }
    
    /*
     * function to delete tb_jenisdokuman
     */
    function delete_tb_jenisdokuman($idJenis)
    {
        return $this->db->delete('tb_jenisdokumen',array('idJenis'=>$idJenis));
    }
}
